CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    price       DOUBLE PRECISION,
    description VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);